#!/bin/bash
# /etc/ax25/ax25-up

# Grab ip address of wireless to set ax port
termip=$(/sbin/ifconfig wlan0 | grep 'inet' | cut -d: -f2 | awk '{print $2}' | cut -d'.' -f 4)
axip="172.1.1.$termip"

#set which ax port
axpt="ondadig1"

#Set Sysctl values
sysctl -w kernel.panic=30
sysctl -w kernel.panic_on_oops=30 

# Run modprobes
/sbin/modprobe ax25
/sbin/modprobe mkiss


##################TEMP
# Attach KISS-device /dev/ttyUSB0 to Port
#working  /usr/sbin/kissattach /dev/ttyUSB0  ondadig1 172.16.2.45 > /tmp/ax25-config.tmp
/usr/sbin/kissattach /dev/ttyUSB0  "$axpt" "$axip"  > /tmp/ax25-config.tmp
  awk '/device/ { print $7 }' /tmp/ax25-config.tmp > /tmp/ax25-config-tmp
  read Device > /tmp/ax25-config-tmp 

# Install Parameters: #############################
# port             (-p) = ondas1
# full/half duplex (-f) = n
# persist          (-r) = 160 (1200 baud) 224 (9600)
# slottime         (-s) =  20  (1200 baud) 30 (9600)
# txdelay          (-t) =  300 (1200 baud) 400 (9600)
#  txtail          (-l) = 20 milliseconds
####################################################


/usr/sbin/kissparms -p "$axpt" -t 400 -s 20 -r 200 -20 -f y


# Start ax25d daemon
  /usr/sbin/ax25d &
  echo "ax25d started"

# Start Mheard daemon
  /usr/sbin/mheardd 
  echo "mheardd Started"

# (End of ax25.up)
