#!/bin/bash
# this script is meant to be run when all terminals need updating. Some things that are updated accordingly:
# - This script
# - AX25 Config
# - IP Static Routing
# - Update Project Onda React App (calling git repo)
