#!/bin/bash
#################UPDATE ONDA TERMINALS##########################################################################
# this script is meant to be run when all terminals need updating. Some things that are updated accordingly:   #
# - This script                                                                                                #
# - AX25 Config                                                                                                #
# - IP Static Routing                                                                                          #
# - Update Project Onda React App (calling git repo)                                                           #
################################################################################################################


####################----Update AX25----##############

sudo cp ax25d.conf /etc/ax25/ax25d.conf
sudo cp axports /etc/ax25/axports
sudo cp ax25-up /etc/ax25/ax25-up
